-- MySQL Script generated by MySQL Workbench
-- Mon Nov 22 23:08:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `amount_assigned` DECIMAL NOT NULL,
  `user_id` INT NOT NULL,
  `amount_spent` DECIMAL NULL,
  `amount_last` DECIMAL NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE,
  INDEX `fk_category_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`pwd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pwd` (
  `pwd_id` INT NOT NULL,
  `pwd_hash` VARCHAR(45) NOT NULL,
  `pwd_salt` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`pwd_id`),
  UNIQUE INDEX `pwd_id_UNIQUE` (`pwd_id` ASC) VISIBLE,
  INDEX `fk_pwd_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_pwd_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`debt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`debt` (
  `debt_id` INT NOT NULL,
  `debt_name` VARCHAR(45) NULL,
  `amount_start` VARCHAR(45) NULL,
  `amount_left` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`debt_id`),
  UNIQUE INDEX `debt_id_UNIQUE` (`debt_id` ASC) VISIBLE,
  INDEX `fk_debt_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_debt_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `transaction_id` INT NOT NULL,
  `amount` DECIMAL NOT NULL,
  `comment` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL,
  `edit_time` TIMESTAMP NULL,
  `category_id` INT NOT NULL,
  `debt_debt_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `transaction_id_UNIQUE` (`transaction_id` ASC) VISIBLE,
  INDEX `fk_transaction_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_transaction_debt1_idx` (`debt_debt_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_debt1`
    FOREIGN KEY (`debt_debt_id`)
    REFERENCES `mydb`.`debt` (`debt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
